# Generated by Django 5.1 on 2024-10-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('appointment_date', models.DateField()),
                ('disease', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
