# Generated by Django 5.1 on 2024-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0002_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='Uttar Pradesh', max_length=100),
            preserve_default=False,
        ),
    ]
