# Generated by Django 5.1 on 2024-10-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0006_review_alter_patient_document_result_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
