# Generated by Django 5.1 on 2024-10-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0009_feedback_delete_patientreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='video',
            new_name='videos',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
